    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present
    - name: Upgrade installed packages
      yum:
        name: '*'
        update_only: true
        state: latest
    - name: Install basic network tools
      yum:
        name:
          - net-tools
          - telnet
        state: present
    - name: Install Ansible requirements
      yum:
        name:
          - python2-PyMySQL
          - python-requests
        state: present
    - name: Add Docker CE repository (Fedora/CentOS/RedHat)
      become: true
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644
    # - name: Install IUS community repository
    #   yum:
    #     name: http://dl.iuscommunity.org/pub/ius/stable/Redhat/7/x86_64/ius-release-1.0-13.ius.el7.noarch.rpm
    #     state: present
    # - name: Deinstall CentOS Git
    #   yum:
    #     name: git
    #     state: absent
    # - name: Install recent Git version
    #   yum:
    #     name: git2u-all
    #     state: present
    - name: Install Docker
      yum:
        name: 
          - docker-ce
          - docker-compose
        state: present
      notify:
        - start docker
    - name: Ensure ntpd is installed
      yum: 
        name: ntp 
        state: present
      notify:
      - restart ntpd
# *********************************************************
# Personalizations
#
    - name: Install zsh
      yum: 
        name: zsh 
        state: present
      notify:
      - configure zsh
