---
- hosts: localhost 
  become: true
  gather_facts: true
  tasks:
    - name: Include RedHat / CentOS specific tasks
      include_tasks: redhat_tasks.yml
      when:
        - ansible_os_family == "RedHat"
    - name: Include Debian / Ubuntu specific tasks
      include_tasks: debian_tasks.yml
      when:
        - ansible_os_family == "Debian"  
  handlers:
    - name: restart ntpd
      service: 
        name: ntpd 
        state: restarted
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
