---
- hosts: all
  become: true
  gather_facts: true
  vars:
    nfs_exports: 
      - "/var/nfs_volume *(rw,sync,no_root_squash)"
  tasks:
    - name: Include RedHat / CentOS specific tasks
      include_tasks: redhat_tasks.yml
      when:
        - ansible_os_family == "RedHat"
    - name: Include Debian / Ubuntu specific tasks
      include_tasks: debian_tasks.yml
      when:
        - ansible_os_family == "Debian"
    - name: Create NFS share
      file:
        path: /var/nfs_volume
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'
  handlers:
    - name: restart ntpd
      service:
        name: ntpd
        state: restarted
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: start nfs
      service:
        name: nfs
        state: started
        enabled: yes
